### ISSUE TITLE
Paths collide on case-insensitive file systems

### ISSUE THREAD

**Issue by ok-mo** [swedishembedded/sdk#16]
The PR https://github.com/swedishembedded/sdk/pull/14 uses two files in the same directory that differ in name by case only.
For case insensitive file systems such as macOS and Windows, one file will overwrite the other. Eg:
```
git clone https://github.com/swedishembedded/sdk.git
Cloning into 'sdk'...
remote: Enumerating objects: 2124, done.
remote: Counting objects: 100% (299/299), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 2124 (delta 115), reused 205 (delta 63), pack-reused 1825
Receiving objects: 100% (2124/2124), 40.28 MiB | 2.52 MiB/s, done.
Resolving deltas: 100% (954/954), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'integrity/infrastructure/Testing.robot'
  'integrity/infrastructure/testing.robot'
```

```
ls sdk/integrity/infrastructure/?esting.robot
sdk/integrity/infrastructure/testing.robot
```
The file
integrity/infrastructure/Testing.robot
does not exist.

**Comment by mkschreder** [comment]
I haven't used a "case-insensitive filesystem" for so long I didn't even think it would be a problem. :)

The problem was introduced in last MR. 

Files with Capital case are intended to be "sharable" across multiple projects (they will contain keywords and follow the robot framework library naming convention - capitalized/nospaces), while lowercase ones contain integrity checks for sdk repository itself. The integrity checks will include the same keyword files but keyword files will be available also for inclusion by application project so that it can more easily apply the same directory patterns. The requirement for a test keyword file to be possible to include as a library is that it must not contain any test cases. 

We can just separate all keyword files into a separate directory to avoid case conflicts.
